live_config_reload = true

[scrolling]

# Maximum number of lines in the scrollback buffer
history = 10000  # Default: 10000

# Number of lines scrolled for every input scroll increment
multiplier = 1  # Default: 3


[keyboard]
# Define keyboard bindings here
# Example placeholder (actual bindings need to be defined based on user preference)
bindings = [
	{ key = "F", mods = "Command|Control", action = "ToggleSimpleFullscreen" },
	# { key = "Key1", mods = "Command", chars = "\u01 \u0031" }, #10 31 0a
	# { key = "Key2", mods = "Command", chars = "\u001 \u0031" },
	# { key = "Key3", mods = "Command", chars = "\u0001 \u0031" },
	# { key = "Key4", mods = "Command", chars = "\u00015" },
	# { key = "Key5", mods = "Command", chars = "\u00026" },
	# { key = "Key6", mods = "Command", chars = "\u00026" },
	# { key = "Key7", mods = "Command", chars = "\u00027" },
	# { key = "Key8", mods = "Command", chars = "\u00028" },
	# { key = "Key9", mods = "Command", chars = "\u00029" },
	# { key = "Key0", mods = "Command", chars = "\u00020" },
]

[font]
size = 16.0

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[window]
decorations = "Transparent"
dynamic_padding = false
opacity = 0.7
blur=true

[window.padding]
x = 35
y = 40
